/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kschultz' at '12/3/14 7:17 PM' with Gradle 2.2
 *
 * @author kschultz, @date 12/3/14 7:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
