FROM netflixoss/java:8

MAINTAINER Ken Schultz <schultzy51@gmail.com>

WORKDIR /data

COPY build/libs/cloud-config-0.0.1.jar /data/cloud-config-0.0.1.jar

CMD java -jar cloud-config-0.0.1.jar

EXPOSE 8888